- NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.1
- NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.0.2
- NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.0.1

notifications:
  recipients:
    - creyes@nuodb.com

before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - sudo chmod 777 django_tests.sh
  - ./django_tests.sh
before_script:
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password baz --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password baz &
  - sleep 2
script:
  - python manage.py test
after_script:
  - sudo dpkg -r nuodb
