language: python

python:
  - "2.7"

env:
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=1.2
  
notifications:
  recipients:
    - creyes@nuodb.com
    - lbayas@nuodb.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com
    
before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 4
  - sudo chmod 777 django_tests.sh

install: "pip install -r requirements.txt --use-mirrors"

before_script:
  - java -jar ${NUODB_HOME}/jar/nuodbmanager.jar --broker localhost --user domain --password bird --command "start process sm database test host localhost archive /var/tmp/nuodb initialize true waitForRunning true"
  - java -jar ${NUODB_HOME}/jar/nuodbmanager.jar --broker localhost --user domain --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password baz' waitForRunning true"
  - echo "create user cloud password 'user';" | ${NUODB_HOME}/bin/nuosql test@localhost --user dba --password baz

script:
  - ./django_tests.sh
  - cd /tmp/nuodb_site
  - python manage.py test

after_script:
  - sudo dpkg -r nuodb
