language: python

python:
  - "2.7"

env:
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 NODE_PATH=/usr/local/bin NUODB_VERSION=1.1.1  
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 NODE_PATH=/usr/local/bin NUODB_VERSION=1.1
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 NODE_PATH=/usr/local/bin NUODB_VERSION=1.0.2
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 NODE_PATH=/usr/local/bin NUODB_VERSION=1.0.1

install:
  - pip install -q Django --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install pynuodb
  - pip install django_pynuodb

notifications:
  recipients:
    - creyes@nuodb.com
    - lbayas@nuodb.com
    - rbuck@nuodb.com
before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 4
  - sudo chmod 777 django_tests.sh

before_script:
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie &
  - sleep 2
  - echo "create user cloud password 'user';" | ${NUODB_ROOT}/bin/nuosql test@localhost --user dba --password goalie

script:
  - ./django_tests.sh
  - cd /tmp/nuodb_site
  - python manage.py test

after_script:
  - sudo dpkg -r nuodb
